name: Deploy to Ubuntu

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies (Golang)
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.0"

      - name: Build the Go app
        run: make build

      - name: Log build directory
        run: echo "Build directory $(pwd)/build"

      - name: Upload application to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          #           source: "build/test-actions-app"
          # target: /root/test-golang-github-actions
          script: |
            mkdir -p /root/test-golang-github-actions
            cp -r ./build/build/test-actions-app /root/test-golang-github-actions/

      - name: Reload Supervisor configuration
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          script: |
            sudo supervisorctl reread
            sudo supervisorctl update
