name: Deploy to Ubuntu

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies (Golang)
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Build the Go app
        run: make build

      - name: Upload application to server
        uses: s0phisticat3d/ssh-action@v2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            mkdir -p /root/test-golang-github-actions
            cp -r ./test-actions-app /root/test-golang-github-actions/

      - name: Reload Supervisor configuration
        uses: s0phisticat3d/ssh-action@v2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            sudo supervisorctl reread
            sudo supervisorctl update
