name: Deploy to Ubuntu

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies (Golang)
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.0"

      - name: Build the Go app
        run: make build

      - name: Debug Build Output
        run: ls -l ./build

      - name: Upload application to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          # script: |
          #   scp -r ./build/test-actions-app ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/root/test-golang-github-actions/
          source: "build/test-actions-app"
          target: "root/test-golang-github-actions"
          # script: |
          #   mkdir -p /root/test-golang-github-actions
          #   cp -rv ./build/test-actions-app /root/test-golang-github-actions

      - name: Reload Supervisor configuration
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          script: |
            sudo supervisorctl reread
            sudo supervisorctl update
